// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// @ts-ignore
const dotenv = require('dotenv');

// Load .env.local explicitly for Prisma CLI commands
dotenv.config({ path: '.env.local' });

import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
